package model.enums;

/**
 * Created by kasra on 2/6/2017.
 */
public enum Status {
    OK(1, "OK"),
    CONFLICT(-1, "CONFLICT"),
    NOT_FOUND(-2, "NOT FOUND"),
    PHONE_NUMBER_EXIST(-3, "PHONE NUMBER EXIST"),
    USERNAME_EXIST(-4, "USERNAME EXIST"),
    USER_NOT_ACTIVATED(-5, "USER NOT ACTIVATED"),
    PHONE_NOT_REGISTERED(-6, "PHONE NOT REGISTERED"),
    USER_NOT_LOGGED_IN(-7, "USER NOT LOGED IN"),
    SUBJECT_EXIST(-8, "SUBJECT EXIST"),
    SERVICE_TYPE_EXIST(-9, "SERVICE TYPE EXIST"),
    TARIFF_NOT_REGISTERED(-10, "TARIFF NOT REGISTERED"),
    RELOAD_NOT_OCCURRED(-11, "RELOAD NOT OCCURRED"),
    MANUFACTURE_EXIST(-12, "MANUFACTURE EXIST"),
    CAR_EXIST(-13, "CAR EXIST"),
    ROLE_MISMATCH(-14, "PARENT AND CHILD ROLE MISMATCH"),
    STATE_EXIST(-15, "STATE EXIST"),
    CITY_EXIST(-16, "CITY EXIST"),
    VOUCHER_CODE_EXIST(-17, "VOUCHER CODE EXIST"),
    SERVICE_PROVIDER_NOT_REGISTERED(-18, "SERVICE PROVIDER NOT REGISTERED"),
    NO_POSSIBILITY_FOR_PAYMENT(-19, "NO POSSIBILITY FOR PAYMENT"),
    PASSWORD_MISMATCH(-24, "PASSWORD AND RE-PASSWORD NOT EQUAL"),
    BAD_PHONE_NUMBER(-23, "BAD PHONE NUMBER"),
    BAD_JSON(-20, "BAD JSON"),
    BAD_USERNAME(-21, "USERNAME DOES NOT MEET REQUIREMENTS"),
    BAD_PASSWORD(-22, "PASSWORD DOES NOT MEET REQUIRMENTS"),
    NOT_MATCH(-30, "DATA NOT MATCH"),
    INCOMPLETE_REGISTERATION(-50, "REGISTERATION PROCESS IS INCOMPLETE"),
    NEEDS_VERIFYING(-51, "DRIVER INFO NEEDS VERIFYING"),
    SERVICE_TYPE_NOT_SET(-52, "DRIVER SERVICE TYPE NOT SET"),
    EXPIRED(-53, "EXPIRED"),
    REQUESTED_SERVICE_NOT_AVAILABLE_IN_THIS_CITY(-151,"REQUESTED SERVICE NOT AVAILABLE IN THIS CITY"),
    USER_BANNED(-200, "USER BANNED"),
    USER_DEACTIVATED(-201, "USER DEACTIVATED"),
    BAD_DATA(-40, "BAD DATA"),
    MAX_UPLOAD_SIZE_EXCEEDED(-41,"MAX UPLOAD SIZE EXCEEDED"),
    TRIP_IN_PROGRESS(-60, "TRIP IN PROGRESS"),
    CAN_NOT_CALCULATE_COST(-61, "CAN NOT CALCULATE COST"),
    DRIVER_LOC_NOT_FOUND(-62, "CAN NOT FIND DRIVER LOCATION"),
    PASSENGER_LOC_NOT_FOUND(-63, "CAN NOT FIND PASSENGER LOCATION"),
    SHIFT_IS_OFF(-64,"DRIVER SHIFT IS OFF"),
    LOW_CREDIT(-65,"CREDIT IS LOW.INCREASE YOUR CREDIT"),
    DRIVER_ON_RIDE(-66,"DRIVER IS ON RIDE"),
    TRIP_WAS_CANCELLED_BY_PASSENGER(-67, "TRIP WAS CANCELLED BY PASSENGER"),
    TRIP_WAS_COMPLETED(-68, "TRIP WAS COMPLETED"),
    TRIP_CANCELLED_ALREADY(-69, "TRIP WAS ALREADY CANCELLED"),
    AV_PLACE_NOT_FOUND(-70,"FAV PLACE NOT FOUND"),
    NO_POSSIBILITY_OF_SERVICE(-100, "AT THE MOMENT THERE IS NO POSSIBILITY OF SERVICE"),
    REQUESTED_SERVICE_NOT_AVAILABLE(-150, "AT THE MOMENT REQUESTED SERVICE NOT AVAILABLE"),
    TRIP_NOT_STARTED(-601, "TRIP NOT STARTED"),
    INCORRECT_VOUCHER_CODE(-602, "VOUCHER CODE IS INCORRECT"),
    TRIP_NOT_ACCEPTED(-603, "TRIP NOT ACCEPTED"),
    VOUCHER_CODE_EXPIRES(-604, "VOUCHER CODE EXPIRES"),
    VOUCHER_CODE_USAGE_LIMIT_EXCEEDED(-605, "VOUCHER CODE USAGE LIMIT EXCEEDED"),

    BAD_REQUEST(-400, "BAD REQUEST"),
    UNAUTHORIZED(-401, "UNAUTHORIZED"),
    TOKEN_EXPIRED(-402, "TOKEN EXPIRED"),
    ACCESS_DENIED(-403, "ACCESS DENIED"),
    RESOURCE_NOT_FOUND(-404,"RESOURCE NOT FOUND"),
    METHOD_NOT_ALLOWED(-405,"REQUESTED METHOD NOT SUPPORTED"),
    UNSUPPORTED_MEDIA_TYPE(-415,"UNSUPPORTED MEDIA TYPE"),

    UNKNOWN_ERROR(-500, "INTERNAL SERVER ERROR AT BACKEND");



    private int statusCode;
    private String statusDesc;

    Status(int statusCode, String status) {
        this.statusCode = statusCode;
        this.statusDesc = status;
    }

    public int getStatusCode() {
        return statusCode;
    }

    public String getStatusDesc() {
        return statusDesc;
    }
}
